Ext.ns('Ext');

Ext.REMOTING_API = {
    "url": "/reporting/router",
    "type": "remoting",
    "actions": {
        "processRestController": [{
            "name": "exportReport",
            "len": 4
        }, {
            "name": "executeJob",
            "len": 1
        }, {
            "name": "getAllProcesseOutputs",
            "len": 1
        }, {
            "name": "getAllProcesses",
            "len": 1
        }, {
            "name": "getAllProcessOutputDeliveries",
            "len": 1
        }, {
            "name": "evaluateSchedule",
            "len": 1
        }, {
            "name": "getProcessStats",
            "len": 1
        }, {
            "name": "getUserProcesses",
            "len": 1
        }, {
            "name": "getExportProcesses",
            "len": 1
        }, {
            "name": "deleteJob",
            "len": 1
        }, {
            "name": "getProcessNotifications",
            "len": 1
        }, {
            "name": "interruptJob",
            "len": 1
        }, {
            "name": "getJobDetails",
            "len": 1
        }, {
            "name": "getScheduleDTO",
            "len": 1
        }, {
            "name": "getSearchedProcesses",
            "len": 1
        }, {
            "name": "exportReportWithTemplate",
            "len": 5
        }],
        "QueryResultHandler": [{
            "name": "getFilterResult",
            "len": 1
        }, {
            "name": "getScheduleSqlQuery",
            "len": 2
        }, {
            "name": "evaluateFormula",
            "len": 3
        }, {
            "name": "getExactQuery",
            "len": 1
        }, {
            "name": "getDisplayQuery",
            "len": 1
        }, {
            "name": "getRunNowQuery",
            "len": 1
        }, {
            "name": "getQueryResult",
            "len": 1
        }],
        "ScheduleCalendarController": [{
            "name": "getAllScheduleCalendars",
            "len": 1
        }, {
            "name": "saveCalendar",
            "len": 1
        }, {
            "name": "getUserScheduleCalendars",
            "len": 1
        }, {
            "name": "deleteScheduleCalendar",
            "len": 1
        }, {
            "name": "getAllCalendarTypes",
            "len": 1
        }],
        "FinanceReportController": [{
            "name": "getFinanceReport",
            "len": 1
        }, {
            "name": "getFinanceReportTemplate",
            "len": 1
        }, {
            "name": "getReportCubes",
            "len": 1
        }],
        "RoleController": [{
            "name": "getRoles",
            "len": 1
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "saveRole",
            "len": 0,
            "formHandler": true
        }, {
            "name": "getUnassignedRolesToHierarchy",
            "len": 1
        }, {
            "name": "assignUsersAndGroups",
            "len": 1
        }, {
            "name": "getRoleAccessHierarchy",
            "len": 1
        }, {
            "name": "getAllRolesWithHierarchy",
            "len": 1
        }, {
            "name": "saveRoleAccessHierarchy",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }],
        "CloudDataSourceController": [{
            "name": "saveDataSource",
            "len": 1
        }, {
            "name": "saveFusionDataSource",
            "len": 1
        }, {
            "name": "getAllCloudDataSources",
            "len": 0
        }, {
            "name": "getCloudDataSourceById",
            "len": 2
        }, {
            "name": "validateFusionDataSource",
            "len": 1
        }],
        "MetaObjectController": [{
            "name": "saveMetaObjectSecurity",
            "len": 1
        }, {
            "name": "getSecurity",
            "len": 3
        }, {
            "name": "getReportAnglesByUserId",
            "len": 2
        }, {
            "name": "getBusinessObjectByType",
            "len": 1
        }, {
            "name": "saveReportorDashboardObject",
            "len": 0,
            "formHandler": true
        }, {
            "name": "loadMetaObject",
            "len": 1
        }, {
            "name": "importTables",
            "len": 3
        }, {
            "name": "deleteJob",
            "len": 1
        }, {
            "name": "saveSqlPhysicalModel",
            "len": 0,
            "formHandler": true
        }, {
            "name": "syncPhysicalTableFromDB",
            "len": 1
        }, {
            "name": "getMetadataEditorItems",
            "len": 1
        }, {
            "name": "getAllOwnedBusinessObjects",
            "len": 1
        }, {
            "name": "getMetaObjectACLPermissions",
            "len": 1
        }, {
            "name": "renameLabels",
            "len": 2
        }, {
            "name": "getDomainACLPermissions",
            "len": 1
        }, {
            "name": "importObjectsUsingSql",
            "len": 2
        }, {
            "name": "getRolesByBusinessObject",
            "len": 1
        }, {
            "name": "getBusinessObjectOrColumnSecurity",
            "len": 2
        }, {
            "name": "syncPhysicalModelFromDB",
            "len": 1
        }, {
            "name": "mapUsersAndRolesToBO",
            "len": 2
        }, {
            "name": "mapUsersAndRolesToDataSet",
            "len": 1
        }, {
            "name": "getMetadataHierarchy",
            "len": 1
        }, {
            "name": "getProperties",
            "len": 1
        }, {
            "name": "getObjectsByUser",
            "len": 1
        }, {
            "name": "getAllMetaObjectsByTenant",
            "len": 1
        }, {
            "name": "isReportOwnerShareAngles",
            "len": 2
        }, {
            "name": "saveLogicalModel",
            "len": 0,
            "formHandler": true
        }, {
            "name": "getSchemas",
            "len": 1
        }, {
            "name": "getDatasetACLPermissions",
            "len": 1
        }, {
            "name": "saveCategoryOrBusinessObject",
            "len": 0,
            "formHandler": true
        }, {
            "name": "saveDomain",
            "len": 0,
            "formHandler": true
        }, {
            "name": "saveListOfValues",
            "len": 2
        }, {
            "name": "attachParentMetaObject",
            "len": 2
        }, {
            "name": "getReportAngles",
            "len": 1
        }, {
            "name": "getACLPermissions",
            "len": 1
        }, {
            "name": "saveFolder",
            "len": 0,
            "formHandler": true
        }, {
            "name": "getAllCustomJobs",
            "len": 1
        }, {
            "name": "mapUsersAndRolesToMO",
            "len": 3
        }, {
            "name": "createBusinessObjectFromSQLTable",
            "len": 1
        }, {
            "name": "shareMetaObjectSecurityToRoleOrUser",
            "len": 2
        }, {
            "name": "getTables",
            "len": 1
        }, {
            "name": "getReportDataSource",
            "len": 1
        }, {
            "name": "getUsersByBusinessObject",
            "len": 1
        }, {
            "name": "getMetaObjectsByType",
            "len": 1
        }, {
            "name": "detachParentMetaObject",
            "len": 1
        }, {
            "name": "getAllBusinessObjects",
            "len": 1
        }],
        "ScriptReportController": [{
            "name": "runScriptReport",
            "len": 2
        }, {
            "name": "runWidgetScriptReport",
            "len": 3
        }],
        "OrbitQuartzController": [{
            "name": "getSchedulerInstanceUniqueNames",
            "len": 1
        }, {
            "name": "getSchedulerDetailsOf",
            "len": 1
        }, {
            "name": "pauseAllOrResumeAllScheduler",
            "len": 1
        }, {
            "name": "migrateAllSchedules",
            "len": 2
        }, {
            "name": "changeSchedulerStateOf",
            "len": 2
        }, {
            "name": "getDefaultTriggerGroupPausedState",
            "len": 0
        }, {
            "name": "clearScheduler",
            "len": 0
        }],
        "CollaborationThreadPostController": [{
            "name": "getThreadPosts",
            "len": 1
        }, {
            "name": "addThreadPost",
            "len": 0,
            "formHandler": true
        }, {
            "name": "loadThumbnail",
            "len": 1
        }, {
            "name": "addFilePost",
            "len": 0,
            "formHandler": true
        }],
        "ReportStatisticsController": [{
            "name": "getReportStatistics",
            "len": 1
        }, {
            "name": "getReportStatisticsById",
            "len": 1
        }, {
            "name": "searchReportStatistics",
            "len": 1
        }],
        "AdvancedSearchController": [{
            "name": "getLastRefreshTime",
            "len": 0
        }, {
            "name": "getRelatedReports",
            "len": 1
        }, {
            "name": "getAdvSearchResults",
            "len": 1
        }],
        "DataFileController": [{
            "name": "getUploadedFilesList",
            "len": 1
        }, {
            "name": "getFileNodes",
            "len": 1
        }, {
            "name": "deleteFile",
            "len": 1
        }],
        "AccessTokenController": [{
            "name": "deleteToken",
            "len": 1
        }, {
            "name": "getExpiredTokens",
            "len": 1
        }, {
            "name": "deleteAllExpiredTokens",
            "len": 1
        }, {
            "name": "saveToken",
            "len": 3
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "getAllTokensByUser",
            "len": 1
        }],
        "CollaborationSnapshotAnnotationController": [{
            "name": "findAllCollabSnapshotAnnotationsByCollabSnapshotId",
            "len": 1
        }, {
            "name": "saveAnnotation",
            "len": 1
        }, {
            "name": "remove",
            "len": 1
        }],
        "CollaborationSnapshotController": [{
            "name": "findAllSnapshotsByThreadId",
            "len": 1
        }, {
            "name": "findAllCollabSnapshotsByThreadId",
            "len": 1
        }, {
            "name": "associateThread",
            "len": 1
        }, {
            "name": "findUnassignedThreadsBySnapshot",
            "len": 1
        }, {
            "name": "findAllThreadsBySnapshot",
            "len": 1
        }, {
            "name": "associateSnapshot",
            "len": 1
        }],
        "WebserviceMetadataController": [{
            "name": "getWsdlDetails",
            "len": 1
        }, {
            "name": "getSoapBody",
            "len": 2
        }, {
            "name": "importWebService",
            "len": 3
        }, {
            "name": "populateColumns",
            "len": 1
        }],
        "GroupController": [{
            "name": "assignUsersAndRoles",
            "len": 1
        }, {
            "name": "saveGroup",
            "len": 0,
            "formHandler": true
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "getGroups",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }],
        "DatasetController": [{
            "name": "createOrUpdateReportNode",
            "len": 4
        }, {
            "name": "getUserJdbcDataSources",
            "len": 1
        }, {
            "name": "importObjectsUsingSql",
            "len": 3
        }, {
            "name": "createWebServiceNode",
            "len": 2
        }, {
            "name": "getBiPublisherMetadata",
            "len": 1
        }, {
            "name": "mergeFileNodeMetadata",
            "len": 1
        }, {
            "name": "getDatasetSqlNode",
            "len": 1
        }, {
            "name": "createBiPublisherReportNode",
            "len": 2
        }, {
            "name": "getDomainObjectProperties",
            "len": 1
        }, {
            "name": "createFileNodes",
            "len": 2
        }, {
            "name": "getSqlNodeMetadata",
            "len": 1
        }, {
            "name": "mergeWebServiceNodeMetadata",
            "len": 1
        }, {
            "name": "getGoogleSheetMetadata",
            "len": 1
        }, {
            "name": "getFileMetadata",
            "len": 1
        }, {
            "name": "getBuildProcessStatistics",
            "len": 1
        }, {
            "name": "mergeSqlNodeMetadata",
            "len": 1
        }, {
            "name": "syncWithReportDefinition",
            "len": 1
        }, {
            "name": "createOrUpdateSqlQuery",
            "len": 3
        }, {
            "name": "loadMergeSqlCommands",
            "len": 1
        }, {
            "name": "getFileNodeMetadata",
            "len": 1
        }, {
            "name": "createSqlNode",
            "len": 2
        }, {
            "name": "populateAndCreateSqlNode",
            "len": 3
        }, {
            "name": "createGoogleSheetNode",
            "len": 2
        }, {
            "name": "getWebServiceMetadata",
            "len": 1
        }],
        "AuthorityController": [{
            "name": "getImportedUsers",
            "len": 1
        }, {
            "name": "getAuthorityAttributes",
            "len": 1
        }, {
            "name": "importAuthorityUsers",
            "len": 2
        }, {
            "name": "deleteAuthority",
            "len": 1
        }, {
            "name": "syncRolesFromAuthorization",
            "len": 1
        }, {
            "name": "createOrUpdate",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }, {
            "name": "getAuthorityUsers",
            "len": 2
        }, {
            "name": "saveAuthority",
            "len": 1
        }, {
            "name": "getAuthorizationsByAuthority",
            "len": 1
        }, {
            "name": "syncAuthorityUsers",
            "len": 1
        }, {
            "name": "isUsersImported",
            "len": 1
        }, {
            "name": "getAllAuthorities",
            "len": 1
        }],
        "FinanceCubeController": [{
            "name": "saveFinanceCube",
            "len": 0,
            "formHandler": true
        }, {
            "name": "loadFinanceCube",
            "len": 1
        }, {
            "name": "deleteFinanceCube",
            "len": 1
        }, {
            "name": "getFinanceCubeDimension",
            "len": 1
        }, {
            "name": "fetchGLRoles",
            "len": 1
        }, {
            "name": "findCubeByErpType",
            "len": 1
        }, {
            "name": "findAllByLoggedInUser",
            "len": 1
        }],
        "DeliveryOptionController": [{
            "name": "onTestEmailServer",
            "len": 2
        }, {
            "name": "getDeliveryOptionById",
            "len": 1
        }, {
            "name": "getAllDetails",
            "len": 1
        }, {
            "name": "onTestSMBConnection",
            "len": 1
        }, {
            "name": "getDefaultDeliveryOptionForType",
            "len": 1
        }, {
            "name": "getPasswordPolicy",
            "len": 1
        }, {
            "name": "getPasswordPolicies",
            "len": 0
        }, {
            "name": "deletePasswordPolicy",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "getAccessableDeliveryOptions",
            "len": 1
        }, {
            "name": "assignUsersAndRoles",
            "len": 1
        }, {
            "name": "makeDefaultDeliveryOption",
            "len": 2
        }, {
            "name": "createOrUpdate",
            "len": 1
        }, {
            "name": "savePasswordPolicy",
            "len": 1
        }, {
            "name": "onTestFTPConnection",
            "len": 1
        }],
        "SalesforceController": [{
            "name": "getDiscoBusinessArea",
            "len": 1
        }, {
            "name": "getDiscoDomains",
            "len": 1
        }, {
            "name": "getSforceTables",
            "len": 1
        }, {
            "name": "getSforceUserReports",
            "len": 1
        }],
        "AdapterNodeController": [{
            "name": "buildQueryColumns",
            "len": 1
        }, {
            "name": "refreshNodeParameters",
            "len": 3
        }, {
            "name": "importWebService",
            "len": 3
        }],
        "FilesController": [{
            "name": "removeAll",
            "len": 0
        }, {
            "name": "uploadFiles",
            "len": 0,
            "formHandler": true
        }, {
            "name": "removeFile",
            "len": 1
        }, {
            "name": "getUserFiles",
            "len": 1
        }],
        "ScheduleInclusiveCalendarController": [{
            "name": "getAllInclusiveCalendars",
            "len": 1
        }, {
            "name": "getCalendarDates",
            "len": 1
        }, {
            "name": "getUserInclusiveCalendars",
            "len": 1
        }, {
            "name": "saveInclusiveCalendar",
            "len": 1
        }, {
            "name": "getCalendarNames",
            "len": 1
        }, {
            "name": "deleteInclusiveCalendar",
            "len": 1
        }],
        "ExcelController": [{
            "name": "prepareRun",
            "len": 3
        }],
        "MigrationController": [{
            "name": "discovererFileUpload",
            "len": 0,
            "formHandler": true
        }],
        "ProcessController": [{
            "name": "getSearchedProcesses",
            "len": 1
        }, {
            "name": "exportReportWithTemplate",
            "len": 5
        }, {
            "name": "getAllProcesses",
            "len": 1
        }, {
            "name": "getJobDetails",
            "len": 1
        }, {
            "name": "getProcessNotifications",
            "len": 1
        }, {
            "name": "getAllProcessOutputDeliveries",
            "len": 1
        }, {
            "name": "getAllProcesseOutputs",
            "len": 1
        }, {
            "name": "getUserProcesses",
            "len": 1
        }, {
            "name": "evaluateSchedule",
            "len": 1
        }, {
            "name": "getProcessStats",
            "len": 1
        }, {
            "name": "deleteJob",
            "len": 1
        }, {
            "name": "exportReport",
            "len": 4
        }, {
            "name": "getExportProcesses",
            "len": 1
        }, {
            "name": "executeJob",
            "len": 1
        }, {
            "name": "getScheduleDTO",
            "len": 1
        }, {
            "name": "interruptJob",
            "len": 1
        }],
        "DeliveryPlanController": [{
            "name": "deleteDeliveryPlan",
            "len": 1
        }, {
            "name": "getDeliveryPlans",
            "len": 1
        }, {
            "name": "saveDevliveryPlan",
            "len": 2
        }, {
            "name": "findDeliveryPlan",
            "len": 1
        }],
        "CollaborationUserController": [{
            "name": "findAllCollabUsersByCollabSnapshotId",
            "len": 1
        }, {
            "name": "findAllCollabUsersByCollabThreadId",
            "len": 1
        }],
        "VersionController": [{
            "name": "getProductVersion",
            "len": 0
        }],
        "ExternalPluginController": [{
            "name": "saveExternalPlugin",
            "len": 1
        }, {
            "name": "findAll",
            "len": 1
        }, {
            "name": "getPluginScripts",
            "len": 1
        }, {
            "name": "update",
            "len": 0,
            "formHandler": true
        }, {
            "name": "save",
            "len": 0,
            "formHandler": true
        }, {
            "name": "getExternalPluginJobs",
            "len": 1
        }, {
            "name": "getExternalPlugin",
            "len": 1
        }, {
            "name": "remove",
            "len": 1
        }, {
            "name": "registerAsJob",
            "len": 2
        }, {
            "name": "loadForm",
            "len": 1
        }],
        "CollaborationThreadController": [{
            "name": "update",
            "len": 0,
            "formHandler": true
        }, {
            "name": "manageThreadCollaborators",
            "len": 1
        }, {
            "name": "findAllByLoggedInUser",
            "len": 1
        }, {
            "name": "findThread",
            "len": 1
        }, {
            "name": "archiveThread",
            "len": 2
        }, {
            "name": "loadForm",
            "len": 1
        }, {
            "name": "remove",
            "len": 1
        }, {
            "name": "findThreadsByLoggedInUser",
            "len": 1
        }, {
            "name": "save",
            "len": 0,
            "formHandler": true
        }, {
            "name": "changeStatus",
            "len": 2
        }],
        "ReportController": [{
            "name": "getAllReports",
            "len": 1
        }, {
            "name": "getAllReportsSharedByUser",
            "len": 1
        }, {
            "name": "deleteReport",
            "len": 1
        }, {
            "name": "getFolderLocation",
            "len": 1
        }, {
            "name": "getTreeNodes",
            "len": 1
        }, {
            "name": "getFavorites",
            "len": 0
        }, {
            "name": "deleteFavourite",
            "len": 1
        }, {
            "name": "getParentId",
            "len": 1
        }, {
            "name": "validateOrganizeReports",
            "len": 3
        }, {
            "name": "generateDefualtYargTemplate",
            "len": 1
        }, {
            "name": "makeDefaultTemplate",
            "len": 2
        }, {
            "name": "saveFinanceReport",
            "len": 0,
            "formHandler": true
        }, {
            "name": "publishLinkAndSave",
            "len": 1
        }, {
            "name": "getReportViews",
            "len": 1
        }, {
            "name": "publishLink",
            "len": 5
        }, {
            "name": "createOrUpdate",
            "len": 1
        }, {
            "name": "getAllReportsSharedByRole",
            "len": 1
        }, {
            "name": "getAllUserReports",
            "len": 0
        }, {
            "name": "getReportsByFolderId",
            "len": 2
        }, {
            "name": "getDetails",
            "len": 1
        }, {
            "name": "evaluateRangeValues",
            "len": 1
        }, {
            "name": "getCustomReport",
            "len": 1
        }, {
            "name": "deleteShortcut",
            "len": 1
        }, {
            "name": "getImageWidgetPic",
            "len": 1
        }, {
            "name": "saveDashboard",
            "len": 3
        }, {
            "name": "renameShortcut",
            "len": 2
        }, {
            "name": "getFolders",
            "len": 1
        }, {
            "name": "modifyPreferences",
            "len": 1
        }, {
            "name": "getFinanceReport",
            "len": 1
        }, {
            "name": "getAllFolders",
            "len": 1
        }, {
            "name": "getORBITTemplates",
            "len": 1
        }, {
            "name": "getCustomJob",
            "len": 1
        }, {
            "name": "getReportParameters",
            "len": 1
        }, {
            "name": "getChartSettings",
            "len": 0
        }, {
            "name": "generateLink",
            "len": 1
        }, {
            "name": "saveCustomJob",
            "len": 1
        }, {
            "name": "getOrganizeTreeNodes",
            "len": 1
        }, {
            "name": "getAllReportFolders",
            "len": 1
        }, {
            "name": "evaluateValue",
            "len": 2
        }, {
            "name": "getRecentItems",
            "len": 0
        }, {
            "name": "getAllTemplates",
            "len": 1
        }, {
            "name": "findReportByObjectKey",
            "len": 1
        }, {
            "name": "getDashboardDefinition",
            "len": 1
        }, {
            "name": "saveCustomReport",
            "len": 3
        }, {
            "name": "makeFavoriteList",
            "len": 1
        }, {
            "name": "makeFavorite",
            "len": 1
        }, {
            "name": "getReportDefinitionFromDrilldown",
            "len": 2
        }, {
            "name": "moveReports",
            "len": 1
        }, {
            "name": "uploadImageWidgetFileToServer",
            "len": 0,
            "formHandler": true
        }, {
            "name": "saveReport",
            "len": 3
        }, {
            "name": "getReportDefinition",
            "len": 1
        }, {
            "name": "getAllMyFolderChildrenReports",
            "len": 1
        }, {
            "name": "deleteFolder",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }, {
            "name": "moveReportsAndAddFavorites",
            "len": 2
        }, {
            "name": "getChildren",
            "len": 1
        }, {
            "name": "getPreferences",
            "len": 1
        }, {
            "name": "deleteTemplate",
            "len": 1
        }],
        "AdminController": [{
            "name": "modifyPreferences",
            "len": 1
        }, {
            "name": "getGlobalPreferences",
            "len": 1
        }],
        "SnapshotController": [{
            "name": "update",
            "len": 0,
            "formHandler": true
        }, {
            "name": "save",
            "len": 0,
            "formHandler": true
        }, {
            "name": "changeStatus",
            "len": 2
        }, {
            "name": "findUnassignedSnapshotsByThread",
            "len": 1
        }, {
            "name": "getSnapshotImageContent",
            "len": 1
        }, {
            "name": "remove",
            "len": 1
        }, {
            "name": "findAllByLoggedInUser",
            "len": 1
        }, {
            "name": "loadForm",
            "len": 1
        }],
        "ExternalPluginGenericController": [{
            "name": "getExternalData",
            "len": 1
        }],
        "FusionController": [{
            "name": "getFusionProperties",
            "len": 1
        }, {
            "name": "fusionJob",
            "len": 0,
            "formHandler": true
        }, {
            "name": "deleteFusionProp",
            "len": 1
        }],
        "PardotController": [{
            "name": "getPardotTables",
            "len": 1
        }, {
            "name": "getTaleoTables",
            "len": 1
        }],
        "DomainController": [{
            "name": "getLogicalTableColumnsList",
            "len": 1
        }, {
            "name": "createOrUpdate",
            "len": 1
        }, {
            "name": "getDomainLocales",
            "len": 1
        }, {
            "name": "saveBusinessObjectFromReport",
            "len": 2
        }, {
            "name": "saveProperties",
            "len": 4
        }, {
            "name": "saveLogicalModel",
            "len": 8
        }, {
            "name": "exportDomain",
            "len": 1
        }, {
            "name": "deleteDomain",
            "len": 1
        }, {
            "name": "getPhysicalColumns",
            "len": 1
        }, {
            "name": "getPhysicalColumnsNotThereInLogicalTable",
            "len": 1
        }, {
            "name": "findBusinessObject",
            "len": 1
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "findUserBusinessObjects",
            "len": 1
        }, {
            "name": "copyDomain",
            "len": 0,
            "formHandler": true
        }, {
            "name": "saveDataSecurity",
            "len": 2
        }, {
            "name": "getTreeNodes",
            "len": 1
        }, {
            "name": "createDateDimensions",
            "len": 5
        }, {
            "name": "saveLocales",
            "len": 2
        }, {
            "name": "forcedeleteMetaObject",
            "len": 2
        }, {
            "name": "pouplateDatasetOutput",
            "len": 3
        }, {
            "name": "findDomainLogicalModels",
            "len": 1
        }, {
            "name": "deleteMetaObject",
            "len": 1
        }, {
            "name": "getLogicalTablesAndRelations",
            "len": 1
        }, {
            "name": "copyLogicalModel",
            "len": 1
        }, {
            "name": "getDetails",
            "len": 1
        }, {
            "name": "saveBusinessObject",
            "len": 2
        }, {
            "name": "loadProperties",
            "len": 1
        }, {
            "name": "findDomainBusinessObjects",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }, {
            "name": "loadBusinessViewTree",
            "len": 1
        }, {
            "name": "getBusineesObjectParentProperties",
            "len": 1
        }, {
            "name": "getLogicalTables",
            "len": 1
        }, {
            "name": "searchUserBusinessObjects",
            "len": 1
        }, {
            "name": "getLogicalTableColumns",
            "len": 1
        }, {
            "name": "getAllDomains",
            "len": 1
        }, {
            "name": "getDatasetBusinessObjectId",
            "len": 1
        }, {
            "name": "getLogicalTablesAndColumns",
            "len": 1
        }, {
            "name": "getLogicalTablesAndRelationsFromDomain",
            "len": 1
        }],
        "LoggerLevelController": [{
            "name": "getLoggersInfo",
            "len": 1
        }, {
            "name": "resetLoggers",
            "len": 1
        }, {
            "name": "saveLoggerLevels",
            "len": 2
        }],
        "OrbitLogController": [{
            "name": "suspendNode",
            "len": 1
        }, {
            "name": "getNodeStatusDetails",
            "len": 1
        }, {
            "name": "updateNodeTypes",
            "len": 2
        }, {
            "name": "getNodeStatusDetailsOf",
            "len": 1
        }, {
            "name": "reinstateNode",
            "len": 1
        }],
        "OracleErpController": [{
            "name": "getOracleReports",
            "len": 1
        }, {
            "name": "getOracleErpAuthorities",
            "len": 1
        }],
        "FinanceCubeDataController": [{
            "name": "loadSegments",
            "len": 2
        }, {
            "name": "getLedgerPeriods",
            "len": 1
        }, {
            "name": "getLedgerCurrencies",
            "len": 1
        }, {
            "name": "getCubeLedgers",
            "len": 1
        }],
        "CustomerController": [{
            "name": "syncSharedContentForTenant",
            "len": 1
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "reloadeLicenses",
            "len": 0
        }, {
            "name": "assignSharedContentRolesToTenants",
            "len": 1
        }, {
            "name": "sendLicenseUserReport",
            "len": 1
        }, {
            "name": "enableOrDisable",
            "len": 3
        }, {
            "name": "getHeaderHtml",
            "len": 0
        }, {
            "name": "loadTenantForm",
            "len": 1
        }, {
            "name": "saveTenant",
            "len": 0,
            "formHandler": true
        }],
        "FileUploadController": [{
            "name": "importFileData",
            "len": 3
        }],
        "ExternalServiceRouterController": [{
            "name": "getExternalServices",
            "len": 0
        }],
        "PublisherReportController": [{
            "name": "runPublisherReport",
            "len": 4
        }],
        "JdbcDriverInfoController": [{
            "name": "delete",
            "len": 1
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "createOrUpdate",
            "len": 1
        }],
        "UserController": [{
            "name": "generateSystemPassword",
            "len": 0
        }, {
            "name": "createOrUpdateUserRoles",
            "len": 1
        }, {
            "name": "createOrUpdate",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }, {
            "name": "getAllUsersByTenant",
            "len": 1
        }, {
            "name": "getUserDtls",
            "len": 1
        }, {
            "name": "resetPassword",
            "len": 0,
            "formHandler": true
        }, {
            "name": "saveHomeChanges",
            "len": 2
        }, {
            "name": "changePassword",
            "len": 2
        }, {
            "name": "saveUser",
            "len": 0,
            "formHandler": true
        }, {
            "name": "saveUserSettings",
            "len": 1
        }, {
            "name": "deleteUserRoles",
            "len": 1
        }, {
            "name": "getRespBusinessRoles",
            "len": 2
        }, {
            "name": "sessionInvalidate",
            "len": 0
        }, {
            "name": "getUserMenuNames",
            "len": 1
        }, {
            "name": "getFilteredUsers",
            "len": 1
        }, {
            "name": "getConcurrentJobDTO",
            "len": 0
        }, {
            "name": "getUsers",
            "len": 1
        }, {
            "name": "getUserMenus",
            "len": 1
        }, {
            "name": "assignGroupsAndRoles",
            "len": 1
        }, {
            "name": "getLoggedInUserInfo",
            "len": 0
        }, {
            "name": "loggedOut",
            "len": 0
        }, {
            "name": "syncUser",
            "len": 1
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "saveProfilePicture",
            "len": 5
        }, {
            "name": "retainSession",
            "len": 0
        }, {
            "name": "getBusinessRoles",
            "len": 1
        }, {
            "name": "usersInUserAssociatedGroups",
            "len": 1
        }, {
            "name": "deleteUser",
            "len": 1
        }],
        "VotingRequestController": [{
            "name": "findAllVotingConfigs",
            "len": 1
        }, {
            "name": "votingSummary",
            "len": 1
        }, {
            "name": "findAllVotingRequestsByThread",
            "len": 1
        }, {
            "name": "changeStatus",
            "len": 2
        }, {
            "name": "createVotingRequest",
            "len": 0,
            "formHandler": true
        }, {
            "name": "doVotingRequest",
            "len": 1
        }],
        "ScheduleController": [{
            "name": "getTimeZones",
            "len": 1
        }, {
            "name": "getUpComingAllEvents",
            "len": 1
        }, {
            "name": "updateSchedule",
            "len": 2
        }, {
            "name": "getUserSchedules",
            "len": 1
        }, {
            "name": "pauseSchedule",
            "len": 1
        }, {
            "name": "getScheduleDetails",
            "len": 1
        }, {
            "name": "unSchedule",
            "len": 1
        }, {
            "name": "getNextFireEvents",
            "len": 2
        }, {
            "name": "deleteSchedule",
            "len": 1
        }, {
            "name": "resumeSchedule",
            "len": 1
        }, {
            "name": "getAllSchedules",
            "len": 1
        }, {
            "name": "getScheduleDTO",
            "len": 1
        }, {
            "name": "getUpComingUserEvents",
            "len": 1
        }, {
            "name": "getSearchedSchedules",
            "len": 1
        }],
        "DataSourceController": [{
            "name": "testConnection",
            "len": 2
        }, {
            "name": "loadDataSourceForm",
            "len": 1
        }, {
            "name": "createDateHierarchy",
            "len": 1
        }, {
            "name": "createOrUpdate",
            "len": 1
        }, {
            "name": "getAllPoolsDetails",
            "len": 0
        }, {
            "name": "getAll",
            "len": 1
        }, {
            "name": "saveDataSource",
            "len": 0,
            "formHandler": true
        }, {
            "name": "shutdownPooledDataSource",
            "len": 1
        }, {
            "name": "startPooledDataSource",
            "len": 1
        }, {
            "name": "getAllDataSources",
            "len": 1
        }, {
            "name": "delete",
            "len": 1
        }, {
            "name": "getDataSource",
            "len": 1
        }],
        "FinanceBatchController": [{
            "name": "saveFinanceBatch",
            "len": 0,
            "formHandler": true
        }, {
            "name": "fetchAllBatches",
            "len": 1
        }, {
            "name": "changeBatchStatus",
            "len": 1
        }, {
            "name": "fetchAllBatchesByStatus",
            "len": 1
        }, {
            "name": "loadFinanceCubeBatch",
            "len": 1
        }],
        "GLLOVController": [{
            "name": "loadGLlovSegments",
            "len": 2
        }],
        "CustomWidgetController": [{
            "name": "findAll",
            "len": 1
        }, {
            "name": "deleteCustomWidget",
            "len": 1
        }, {
            "name": "getCustomWidgetCode",
            "len": 1
        }, {
            "name": "saveCustomWidget",
            "len": 0,
            "formHandler": true
        }, {
            "name": "getCustomWidget",
            "len": 1
        }],
        "MenuController": [{
            "name": "deleteMenu",
            "len": 1
        }, {
            "name": "getAllMenus",
            "len": 1
        }, {
            "name": "createOrUpdate",
            "len": 1
        }, {
            "name": "getAllModulesByRoleId",
            "len": 1
        }, {
            "name": "saveMappedMenus",
            "len": 2
        }],
        "orbitMarketPlaceController": [{
            "name": "installWidget",
            "len": 1
        }, {
            "name": "getAllWidgets",
            "len": 1
        }],
        "TranslatedLabelController": [{
            "name": "resetLabels",
            "len": 0
        }, {
            "name": "getAllLocales",
            "len": 1
        }, {
            "name": "getTranslatedLabels",
            "len": 1
        }, {
            "name": "saveLabelList",
            "len": 2
        }, {
            "name": "getAllScreenNames",
            "len": 1
        }],
        "ConcurrentJobController": [{
            "name": "pauseJob",
            "len": 1
        }, {
            "name": "deleteJob",
            "len": 1
        }, {
            "name": "getAllJobTypes",
            "len": 1
        }, {
            "name": "resumeJob",
            "len": 1
        }, {
            "name": "unScheduleJob",
            "len": 1
        }, {
            "name": "interruptJob",
            "len": 1
        }],
        "LicenseInfoController": [{
            "name": "getLicenseInfo",
            "len": 0
        }],
        "ShareFolderAndReportController": [{
            "name": "getSecurity",
            "len": 1
        }, {
            "name": "getRoleUserAndGroups",
            "len": 1
        }],
        "AddonController": [{
            "name": "getAllAddons",
            "len": 1
        }]
    },
    "timeout": 3600000
};

Ext.POLLING_URLS = {
    "processCompletePolling": "/reporting/poll/ProcessController/processCompletePolling/processCompletePolling",
    "processCompletePolling": "/reporting/poll/processRestController/processCompletePolling/processCompletePolling"
};